### PR TITLE
trying to add workflows

### PR DESCRIPTION
**Pull request by pclausen**

### CODE REVIEW

**Comment by pclausen** [comment]
@ErikSchierboom It worked today from my laptop and it did not work from gitpod. I dont quite understand why, but then that is how it is...

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@pclausen That's perfect. Thanks.

**Comment by ErikSchierboom** [comment]
The workflows are running, we're just missing some configuration. @iHiD could you give this repo access to the username/password secrets? See https://github.com/exercism/fortran-test-runner/runs/2912215723?check_suite_focus=true

**Comment by iHiD** [comment]
Done.

**Comment by ErikSchierboom** [comment]
@pclausen It now works! I've just successfully submitted the hello-world exercise on exercism.lol:

image

**Comment by iHiD** [comment]
Exciting!

**Pull request merged**
